spring.application.name=Trabalho_DS_2026


# Conexão com o banco (substitua o nome_do_seu_banco, root e sua_senha)
spring.datasource.url=jdbc:mysql://localhost:3306/Trabalho_DS_2026?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Estratégia de criação das tabelas
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL sendo executado no console (ótimo para testar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true