spring.application.name=Trabalho_DS_2026

# Conexão segura seguindo as chaves do enunciado + os dados atuais do seu Neon
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-divine-hall-acxivo44-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DATABASE_USERNAME:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD:npg_EZXGMa8Q6hbc}

# Configurações do Driver e Dialeto do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Estratégia de tabelas (Como já criou, o "update" apenas mantém e confere)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true